# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'professor_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class ProfessorWindowUI(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.background.setStyleSheet(
            "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(198, 198, 198, 255), stop:1 rgba(234, 234, 234, 255));")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.header = QtWidgets.QFrame(self.background)
        self.header.setGeometry(QtCore.QRect(0, 0, 1280, 65))
        self.header.setStyleSheet(
            "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(225, 112, 111, 255), stop:1 rgba(195, 96, 96, 255));\n"
            "\n"
            "border-bottom: 2px solid black;\n"
            "\n"
            "padding: 0;")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.account = QtWidgets.QPushButton(self.header)
        self.account.setGeometry(QtCore.QRect(1160, 17, 81, 31))
        self.account.setStyleSheet("font-size: 18px;\n"
                                   "font-family: montserrat;\n"
                                   "font-weight: 400;\n"
                                   "\n"
                                   "background: transparent;\n"
                                   "\n"
                                   "border: 0;\n"
                                   "padding: 0;")
        self.account.setObjectName("account")
        self.test_name = QtWidgets.QLineEdit(self.background)
        self.test_name.setGeometry(QtCore.QRect(240, 115, 800, 50))
        self.test_name.setStyleSheet("border: 2px solid black;\n"
                                     "border-radius: 17px;\n"
                                     "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(198, 198, 198, 255), stop:1 rgba(234, 234, 234, 255));\n"
                                     "\n"
                                     "padding: 5px;\n"
                                     "\n"
                                     "font-size: 18px;\n"
                                     "font-family: montserrat;\n"
                                     "font-weight: 400;")
        self.test_name.setText("")
        self.test_name.setObjectName("test_name")
        self.question = QtWidgets.QLineEdit(self.background)
        self.question.setGeometry(QtCore.QRect(240, 220, 800, 50))
        self.question.setStyleSheet("border: 2px solid black;\n"
                                    "border-radius: 17px;\n"
                                    "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(198, 198, 198, 255), stop:1 rgba(234, 234, 234, 255));\n"
                                    "\n"
                                    "padding: 5px;\n"
                                    "\n"
                                    "font-size: 18px;\n"
                                    "font-family: montserrat;\n"
                                    "font-weight: 400;")
        self.question.setText("")
        self.question.setObjectName("question")
        self.wrong_answer_one = QtWidgets.QLineEdit(self.background)
        self.wrong_answer_one.setGeometry(QtCore.QRect(240, 310, 800, 50))
        self.wrong_answer_one.setStyleSheet("border: 2px solid black;\n"
                                            "border-radius: 17px;\n"
                                            "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(198, 198, 198, 255), stop:1 rgba(234, 234, 234, 255));\n"
                                            "\n"
                                            "padding: 5px;\n"
                                            "\n"
                                            "font-size: 18px;\n"
                                            "font-family: montserrat;\n"
                                            "font-weight: 400;")
        self.wrong_answer_one.setText("")
        self.wrong_answer_one.setObjectName("wrong_answer_one")
        self.wrong_answer_two = QtWidgets.QLineEdit(self.background)
        self.wrong_answer_two.setGeometry(QtCore.QRect(240, 380, 800, 50))
        self.wrong_answer_two.setStyleSheet("border: 2px solid black;\n"
                                            "border-radius: 17px;\n"
                                            "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(198, 198, 198, 255), stop:1 rgba(234, 234, 234, 255));\n"
                                            "\n"
                                            "padding: 5px;\n"
                                            "\n"
                                            "font-size: 18px;\n"
                                            "font-family: montserrat;\n"
                                            "font-weight: 400;")
        self.wrong_answer_two.setText("")
        self.wrong_answer_two.setObjectName("wrong_answer_two")
        self.wrong_answer_three = QtWidgets.QLineEdit(self.background)
        self.wrong_answer_three.setGeometry(QtCore.QRect(240, 450, 800, 50))
        self.wrong_answer_three.setStyleSheet("border: 2px solid black;\n"
                                              "border-radius: 17px;\n"
                                              "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(198, 198, 198, 255), stop:1 rgba(234, 234, 234, 255));\n"
                                              "\n"
                                              "padding: 5px;\n"
                                              "\n"
                                              "font-size: 18px;\n"
                                              "font-family: montserrat;\n"
                                              "font-weight: 400;")
        self.wrong_answer_three.setText("")
        self.wrong_answer_three.setObjectName("wrong_answer_three")
        self.correct_answer = QtWidgets.QLineEdit(self.background)
        self.correct_answer.setGeometry(QtCore.QRect(240, 520, 800, 50))
        self.correct_answer.setStyleSheet("border: 2px solid black;\n"
                                          "border-radius: 17px;\n"
                                          "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(198, 198, 198, 255), stop:1 rgba(234, 234, 234, 255));\n"
                                          "\n"
                                          "padding: 5px;\n"
                                          "\n"
                                          "font-size: 18px;\n"
                                          "font-family: montserrat;\n"
                                          "font-weight: 400;")
        self.correct_answer.setText("")
        self.correct_answer.setObjectName("correct_answer")
        self.add_question = QtWidgets.QPushButton(self.background)
        self.add_question.setGeometry(QtCore.QRect(240, 620, 250, 50))
        self.add_question.setStyleSheet("border: 2px solid black;\n"
                                        "border-radius: 17px;\n"
                                        "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(198, 198, 198, 255), stop:1 rgba(234, 234, 234, 255));\n"
                                        "\n"
                                        "font-size: 18px;\n"
                                        "font-family: montserrat;\n"
                                        "font-weight: 400;")
        self.add_question.setObjectName("add_question")
        self.done = QtWidgets.QPushButton(self.background)
        self.done.setGeometry(QtCore.QRect(790, 620, 250, 50))
        self.done.setStyleSheet("border: 2px solid black;\n"
                                        "border-radius: 17px;\n"
                                        "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(225, 112, 111, 255), stop:1 rgba(195, 96, 96, 255));\n"
                                        "\n"
                                        "font-size: 18px;\n"
                                        "font-family: montserrat;\n"
                                        "font-weight: 400;")
        self.done.setObjectName("add_question")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EquTest"))
        self.test_name.setPlaceholderText(_translate("MainWindow", "Назва тесту"))
        self.question.setPlaceholderText(_translate("MainWindow", "Питання"))
        self.wrong_answer_one.setPlaceholderText(_translate("MainWindow", "Неправильна відповідь"))
        self.wrong_answer_two.setPlaceholderText(_translate("MainWindow", "Неправильна відповідь"))
        self.wrong_answer_three.setPlaceholderText(_translate("MainWindow", "Неправильна відповідь"))
        self.correct_answer.setPlaceholderText(_translate("MainWindow", "Правильна відповідь"))
        self.add_question.setText(_translate("MainWindow", "Додати питання"))
        self.done.setText(_translate("MainWindow", "Готово"))
        self.account.setText(_translate("MainWindow", "Профіль"))
