# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class TestWindowUI(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.background.setStyleSheet(
            "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(198, 198, 198, 255), stop:1 rgba(234, 234, 234, 255));\n"
            "\n"
            "padding: 95px 30px;")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.header = QtWidgets.QFrame(self.background)
        self.header.setGeometry(QtCore.QRect(0, 0, 1280, 65))
        self.header.setStyleSheet(
            "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(225, 112, 111, 255), stop:1 rgba(195, 96, 96, 255));\n"
            "\n"
            "border-bottom: 2px solid black;\n"
            "\n"
            "padding: 0;")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.account = QtWidgets.QPushButton(self.background)
        self.account.setGeometry(QtCore.QRect(1160, 17, 81, 31))
        self.account.setStyleSheet("font-size: 18px;\n"
                                   "font-family: montserrat;\n"
                                   "font-weight: 400;\n"
                                   "\n"
                                   "background: transparent;\n"
                                   "\n"
                                   "border: 0;\n"
                                   "padding: 0;")
        self.account.setObjectName("account")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EquTest"))
        self.account.setText(_translate("MainWindow", "Профіль"))