# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_statistic_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class StatisticUI(QtWidgets.QMainWindow):
    def setupUi(self, StudentStatistic):
        StudentStatistic.setObjectName("StudentStatistic")
        StudentStatistic.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(StudentStatistic)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.background.setStyleSheet(
            "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(198, 198, 198, 255), stop:1 rgba(234, 234, 234, 255));\n"
            "\n"
            "padding: 95px 30px;")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.header = QtWidgets.QFrame(self.background)
        self.header.setGeometry(QtCore.QRect(0, 0, 1280, 65))
        self.header.setStyleSheet(
            "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(225, 112, 111, 255), stop:1 rgba(195, 96, 96, 255));\n"
            "\n"
            "border-bottom: 2px solid black;\n"
            "\n"
            "padding: 0;")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.test_name = QtWidgets.QLabel(self.background)
        self.test_name.setGeometry(QtCore.QRect(80, 130, 730, 31))
        self.test_name.setStyleSheet("background: transparent;\n"
                                     "padding: 0;\n"
                                     "\n"
                                     "font-size: 18px;\n"
                                     "font-family: montserrat;\n"
                                     "font-weight: 400;")
        self.test_name.setObjectName("test_name")
        self.right_answers = QtWidgets.QLabel(self.background)
        self.right_answers.setGeometry(QtCore.QRect(820, 130, 191, 31))
        self.right_answers.setStyleSheet("background: transparent;\n"
                                         "padding: 0;\n"
                                         "\n"
                                         "font-size: 18px;\n"
                                         "font-family: montserrat;\n"
                                         "font-weight: 400;")
        self.right_answers.setObjectName("right_answers")
        self.percent = QtWidgets.QLabel(self.background)
        self.percent.setGeometry(QtCore.QRect(1080, 130, 91, 31))
        self.percent.setStyleSheet("background: transparent;\n"
                                   "padding: 0;\n"
                                   "\n"
                                   "font-size: 18px;\n"
                                   "font-family: montserrat;\n"
                                   "font-weight: 400;")
        self.percent.setObjectName("percent")
        StudentStatistic.setCentralWidget(self.centralwidget)

        self.retranslateUi(StudentStatistic)
        QtCore.QMetaObject.connectSlotsByName(StudentStatistic)

    def retranslateUi(self, StudentStatistic):
        _translate = QtCore.QCoreApplication.translate
        StudentStatistic.setWindowTitle(_translate("StudentStatistic", "EquTest"))
        self.test_name.setText(_translate("StudentStatistic", "Тест"))
        self.right_answers.setText(_translate("StudentStatistic", "Правильні відповіді"))
        self.percent.setText(_translate("StudentStatistic", "Відсоток"))
