# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'test_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class TestWidget(QtWidgets.QWidget):
    def __init__(self, test_name: str, grade: int):
        super().__init__()
        self.__test_name__ = test_name
        self.__grade__ = grade

        self.setupUi()

    def setupUi(self):
        self.resize(580, 300)
        self.background = QtWidgets.QFrame(self)
        self.background.setGeometry(QtCore.QRect(0, 0, 580, 300))
        self.background.setStyleSheet(
            "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(225, 112, 111, 255), stop:1 rgba(195, 96, 96, 255));\n"
            "\n"
            "border-radius: 20px;\n"
            "border: 2px solid black;")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.start_button = QtWidgets.QPushButton(self.background)
        self.start_button.setGeometry(QtCore.QRect(30, 220, 200, 50))
        self.start_button.setStyleSheet("border: 2px solid black;\n"
                                        "border-radius: 17px;\n"
                                        "background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(198, 198, 198, 255), stop:1 rgba(234, 234, 234, 255));\n"
                                        "\n"
                                        "font-size: 18px;\n"
                                        "font-family: montserrat;\n"
                                        "font-weight: 400;"
                                        "\n"
                                        "padding: 0;")
        self.start_button.setObjectName("start_button")
        self.__title__ = QtWidgets.QLabel(self.background)
        self.__title__.setGeometry(QtCore.QRect(35, 30, 491, 31))
        self.__title__.setStyleSheet("background: transparent;\n"
                                     "border: 0;\n"
                                     "\n"
                                     "font-size: 24px;\n"
                                     "font-family: montserrat;\n"
                                     "font-weight: 500;"
                                     "\n"
                                     "padding: 0;")
        self.__title__.setObjectName("__title__")
        self.questions_amount = QtWidgets.QLabel(self.background)
        self.questions_amount.setGeometry(QtCore.QRect(36, 70, 491, 31))
        self.questions_amount.setStyleSheet("background: transparent;\n"
                                            "border: 0;\n"
                                            "\n"
                                            "font-size: 24px;\n"
                                            "font-family: montserrat;\n"
                                            "font-weight: 400;"
                                            "\n"
                                            "padding: 0;")
        self.questions_amount.setObjectName("questions_amount")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    @staticmethod
    def open_test_window(student_window, test_window) -> None:
        student_window.hide()
        test_window.show()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "Test"))
        self.start_button.setText(_translate("self", "Почати"))
        self.__title__.setText(_translate("self", f"{self.__test_name__}"))
        self.questions_amount.setText(_translate("self", f"Максимальний бал: {self.__grade__}"))
